#! /bin/sh
# coding: utf-8
exec ruby -S -x "$0" "$@"
#! ruby

prefix = Dir::home
open(prefix+"/shuzo/maxim") do |f|
    f.gets("### maxim data ###")
    data = f.read()
    fortunes = data.split("%")
    puts fortunes[rand(fortunes.length)]
end

puts "                                -- Shuzo Matsuoka\n"
puts "~~~~~~~~~~~\\/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

exec("imgcat "+prefix+"/shuzo/shuzo.png")

