#! /bin/sh
# coding: utf-8
exec ruby -S -x "$0" "$@"
#! ruby
  
open('maxim') do |f|
    f.gets("### maxim data ###")
    data = f.read()
    fortunes = data.split("%")
    puts fortunes[rand(fortunes.length)]
end

puts "                                -- Shuzo Matsuoka\n"
puts "~~~~~~~~~~~\\/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

exec("./imgcat shuzo.png")

